// Shared data schema for Crystal-Ball — imported by both the SPA (src/) and the
// data pipeline (pipeline/). See PLAN.md §5 for the rationale.

export type AssetClass =
  | "equity-index"
  | "equity-single"
  | "rates"
  | "fx"
  | "metal"
  | "energy"
  | "crypto";

export interface Asset {
  /** Stable id used to reference the asset from events/links, e.g. "SPX". */
  id: string;
  label: string;
  class: AssetClass;
}

export type EventCategory =
  | "monetary-policy"
  | "economic-data"
  | "earnings"
  | "commodity-energy"
  | "political"
  | "geopolitical"
  | "crypto"
  | "market-structure";

export type Direction = "up" | "down" | "neutral";
export type Magnitude = "low" | "med" | "high";

/** How an outcome is expected to move a specific asset. */
export interface AssetImpact {
  asset: string; // Asset.id
  direction: Direction;
  magnitude: Magnitude;
}

/** Provenance of an outcome's probability weight (PLAN §6). */
export type WeightSource =
  | "market-implied"
  | "consensus"
  | "historical"
  | "model";

/** A single weighted scenario for an event (populated from Phase 2 on). */
export interface Outcome {
  id: string;
  label: string;
  weight: number; // probability, 0..1
  weightSource: WeightSource;
  assetImpacts: AssetImpact[];
  /** One-line explanation of the scenario and its market reaction. */
  rationale?: string;
  /** What the probability weight is derived from (shown in the UI). */
  provenance?: string;
}

export type LinkTier = "structural" | "historical";

/** A correlation link between an event and an asset (PLAN §7). */
export interface EventAssetLink {
  asset: string; // Asset.id
  tier: LinkTier;
  strength: number; // 0..1
  stats?: {
    n: number;
    avgAbsMovePct: number;
    directionHitRate: number;
  };
}

export interface MarketEvent {
  id: string;
  title: string;
  category: EventCategory;
  /** ISO 8601 timestamp of the (expected) event time. */
  scheduledAt: string;
  /** false = anticipated event with uncertain timing. */
  isScheduled: boolean;
  /** Prior on how market-moving this event tends to be, 0..1. */
  expectedImpact: number;
  /** Provider id this event came from, e.g. "fred" or "fixture". */
  source: string;
  /** Event→asset correlation links (structural in Phase 0/1). */
  links: EventAssetLink[];
  /** Weighted outcome scenarios (added in Phase 2). */
  outcomes?: Outcome[];
}

/** One line of the generated digest (PLAN §2 surface). */
export interface DigestItem {
  eventId: string;
  title: string;
  scheduledAt: string;
  category: EventCategory;
  expectedImpact: number;
  /** Highest-strength linked assets, for a quick "what it touches" read. */
  topAssets: string[];
}

/** A generated daily/weekly digest of what's coming. */
export interface Digest {
  generatedAt: string;
  headline: string;
  /** Notable events in the next ~7 days. */
  daily: DigestItem[];
  /** Notable events in the next ~30 days. */
  weekly: DigestItem[];
}

/** One row of the calibration/reliability scorecard (PLAN §6, §11). */
export interface CalibrationRow {
  kind: string;
  kindLabel: string;
  asset: string;
  n: number;
  avgAbsMovePct: number;
  directionHitRate: number;
  strength: number;
}

/** The single artifact the SPA loads (data/events.json). */
export interface DataBundle {
  /** ISO timestamp the bundle was generated by the pipeline. */
  generatedAt: string;
  assets: Asset[];
  events: MarketEvent[];
  digest: Digest;
  /** Event-study reliability scorecard (Phase 4). */
  calibration: CalibrationRow[];
}

/** Multi-scale timeline horizons (PLAN §2.4). */
export const TIMELINE_SCALES = [
  { id: "daily", label: "Daily", days: 5 },
  { id: "weekly", label: "Weekly", days: 28 },
  { id: "monthly", label: "Monthly", days: 92 },
  { id: "quarterly", label: "Quarterly", days: 366 },
  { id: "annual", label: "Annual", days: 1095 },
  { id: "decade", label: "Decade", days: 3653 },
] as const;

export type TimelineScaleId = (typeof TIMELINE_SCALES)[number]["id"];
